# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Pruthvi
subtitle:       
paginate:       10
baseurl:        "/pruthvisite"
url:            "https://phmehta95.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
name:         Pruthvi Mehta
url:
email:

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
