# Permalinks
permalink:      /:2017-:08-:23/:title

# Setup
title:          Pruthvi Mehta
subtitle:       isn't that good at particle physics, but really likes it
paginate:       10
baseurl:        "/pruthvisite"
url:            "https://phmehta95.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:		Pruthvi Mehta
name:         Pruthvi Mehta
url:
email:

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
